name: Testing Self Hosted Runner
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: [self-hosted, linux, test]
    steps:
      - name: Echo content
        run: |
          echo Ok
          sleep 15s
